void printWebsite(WiFiClient client) {
client.println("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>");
client.println("<script type=\"text/javascript\" id=\"webrtc-control\">");
client.println("$(document).ready(function() {");
client.println("  var slider = document.getElementById(\"r1\");");
client.println("  var output = document.getElementById(\"valueR1\");");
client.println("  output.innerHTML = slider.value + \"%\"; // Display the default slider value");
client.println("  // Update the current slider value (each time you drag the slider handle)");
client.println("  slider.oninput = function() {");
client.println("    output.innerHTML = this.value + \"%\";");
client.println("  }");
client.println("  var slider2 = document.getElementById(\"g1\");");
client.println("  var output2 = document.getElementById(\"valueG1\");");
client.println("  output2.innerHTML = slider2.value + \"%\"; // Display the default slider value");
client.println("  // Update the current slider value (each time you drag the slider handle)");
client.println("  slider2.oninput = function() {");
client.println("    output2.innerHTML = this.value + \"%\";");
client.println("  }");
client.println("  var slider3 = document.getElementById(\"b1\");");
client.println("  var output3 = document.getElementById(\"valueB1\");");
client.println("  output3.innerHTML = slider3.value + \"%\"; // Display the default slider value");
client.println("  // Update the current slider value (each time you drag the slider handle)");
client.println("  slider3.oninput = function() {");
client.println("    output3.innerHTML = this.value + \"%\";");
client.println("  }");
client.println("  var sliderDivider = document.getElementById(\"divider\");");
client.println("  var outputDivider = document.getElementById(\"valueDivider\");");
client.println("  outputDivider.innerHTML = sliderDivider.value + \"%\"; // Display the default slider value");
client.println("  // Update the current slider value (each time you drag the slider handle)");
client.println("  sliderDivider.oninput = function() {");
client.println("    outputDivider.innerHTML = this.value + \"%\";");
client.println("  }");
client.println("  var slider4 = document.getElementById(\"r2\");");
client.println("  var output4 = document.getElementById(\"valueR2\");");
client.println("  output4.innerHTML = slider4.value + \"%\"; // Display the default slider value");
client.println("  // Update the current slider value (each time you drag the slider handle)");
client.println("  slider4.oninput = function() {");
client.println("    output4.innerHTML = this.value + \"%\";");
client.println("  }");
client.println("  var slider5 = document.getElementById(\"g2\");");
client.println("  var output5 = document.getElementById(\"valueG2\");");
client.println("  output5.innerHTML = slider5.value + \"%\"; // Display the default slider value");
client.println("  // Update the current slider value (each time you drag the slider handle)");
client.println("  slider5.oninput = function() {");
client.println("    output5.innerHTML = this.value + \"%\";");
client.println("  }");
client.println("  var slider6 = document.getElementById(\"b2\");");
client.println("  var output6 = document.getElementById(\"valueB2\");");
client.println("  output6.innerHTML = slider6.value + \"%\"; // Display the default slider value");
client.println("  // Update the current slider value (each time you drag the slider handle)");
client.println("  slider6.oninput = function() {");
client.println("    output6.innerHTML = this.value + \"%\";");
client.println("  }");
client.println("  jQuery('<div class=\"quantity-nav\"><div class=\"quantity-button quantity-up\">+</div><div class=\"quantity-button quantity-down\">-</div></div>').insertAfter('.quantity input');");
client.println("  jQuery('.quantity').each(function () {");
client.println("    var spinner = jQuery(this),");
client.println("      input = spinner.find('input[type=\"number\"]'),");
client.println("      btnUp = spinner.find('.quantity-up'),");
client.println("      btnDown = spinner.find('.quantity-down'),");
client.println("      min = input.attr('min'),");
client.println("      max = input.attr('max');");
client.println("    btnUp.click(function () {");
client.println("      var oldValue = parseFloat(input.val());");
client.println("      if (oldValue >= max) {");
client.println("        var newVal = oldValue;");
client.println("      } else {");
client.println("        var newVal = oldValue + 1;");
client.println("      }");
client.println("      spinner.find(\"input\").val(newVal);");
client.println("      spinner.find(\"input\").trigger(\"change\");");
client.println("    });");
client.println("    btnDown.click(function () {");
client.println("      var oldValue = parseFloat(input.val());");
client.println("      if (oldValue <= min) {");
client.println("        var newVal = oldValue;");
client.println("      } else {");
client.println("        var newVal = oldValue - 1;");
client.println("      }");
client.println("      spinner.find(\"input\").val(newVal);");
client.println("      spinner.find(\"input\").trigger(\"change\");");
client.println("    });");
client.println("  });");
client.println("  ");
client.println("  if (navigator.userAgent.search(\"Firefox\") >= 0) {");
client.println("    jQuery(\".quantity-nav\").css(\"float\", \"left\");");
client.println("    jQuery(\".quantity-nav\").css(\"position\", \"relative\");");
client.println("  }else{");
client.println("    jQuery(\".quantity-nav\").css(\"position\", \"absolute\");");
client.println("    jQuery(\".quantity-nav\").css(\"margin-left\", \"65px\");");
client.println("  }");
client.println("  ");
client.println("})");
client.println("</script>");
client.println("<style>");
client.println("  ");
client.println("  main {");
client.println("    font-size: 99%;");
client.println("    font-family: \"Arial\", sans-serif ;");
client.println("    line-height: 1.5;");
client.println("    text-align: center;");
client.println("    margin: 0 auto;");
client.println("    width: 80%;");
client.println("    clear: both;");
client.println("  }");
client.println("  .choose{");
client.println("    display: flex;");
client.println("    flex-flow: column;");
client.println("  }");
client.println("  .counterWrapper{");
client.println("    width: 60px;");
client.println("    margin: 0 auto;");
client.println("  }");
client.println("  ");
client.println("  .quantity{");
client.println("    position: relative;");
client.println("  }");
client.println("  input[type=number]::-webkit-inner-spin-button,");
client.println("  input[type=number]::-webkit-outer-spin-button");
client.println("  {");
client.println("    -webkit-appearance: none;");
client.println("    margin: 0;");
client.println("  }");
client.println("  input[type=number]");
client.println("  {");
client.println("    -moz-appearance: textfield;");
client.println("  }");
client.println("  .quantity input {");
client.println("    width: 45px;");
client.println("    height: 42px;");
client.println("    line-height: 1.65;");
client.println("    float: left;");
client.println("    display: block;");
client.println("    padding: 0;");
client.println("    margin: 0;");
client.println("    padding-left: 20px;");
client.println("    border: 1px solid #eee;");
client.println("  }");
client.println("  .quantity input:focus {");
client.println("    outline: 0;");
client.println("  }");
client.println("  .quantity-nav {");
client.println("    height: 42px;");
client.println("  }");
client.println("  .quantity-button {");
client.println("    position: relative;");
client.println("    cursor: pointer;");
client.println("    border-left: 1px solid #eee;");
client.println("    width: 20px;");
client.println("    text-align: center;");
client.println("    color: #333;");
client.println("    font-size: 13px;");
client.println("    font-family: \"Trebuchet MS\", Helvetica, sans-serif !important;");
client.println("    line-height: 1.7;");
client.println("    -webkit-transform: translateX(-100%);");
client.println("    transform: translateX(-100%);");
client.println("    -webkit-user-select: none;");
client.println("    -moz-user-select: none;");
client.println("    -ms-user-select: none;");
client.println("    -o-user-select: none;");
client.println("    user-select: none;");
client.println("  }");
client.println("  .quantity-button.quantity-up {");
client.println("    position: absolute;");
client.println("    height: 50%;");
client.println("    top: 0;");
client.println("    border-bottom: 1px solid #eee;");
client.println("  }");
client.println("  .quantity-button.quantity-down {");
client.println("    position: absolute;");
client.println("    bottom: -1px;");
client.println("    height: 50%;");
client.println("  }");
client.println("  #programmChoose .submitWrapper{");
client.println("    margin-top: 20px;");
client.println("  }");
client.println("  #programmChoose .button {");
client.println("    background-color: lightblue;");
client.println("    border: none;");
client.println("    color: white;");
client.println("    padding: 10px 10px;");
client.println("    text-align: center;");
client.println("    text-decoration: none;");
client.println("    font-size: 16px;");
client.println("  }");
client.println("  #codeArea {");
client.println("    margin: 20px 0 20px 0;");
client.println("  }");
client.println("  #codeArea .submitWrapper {");
client.println("    margin-top: 20px;");
client.println("  }");
client.println("  #codeArea .button {");
client.println("    background-color: lightblue;");
client.println("    border: none;");
client.println("    color: white;");
client.println("    padding: 10px 20px;");
client.println("    text-align: center;");
client.println("    text-decoration: none;");
client.println("    font-size: 16px;");
client.println("  }");
client.println("  #rgbSettings{");
client.println("    width: 80%;");
client.println("    display: flex;");
client.println("    flex-flow: row;");
client.println("    margin: auto;");
client.println("    margin-top: 5%;");
client.println("  }");
client.println("  #rgbSettings #chooserForms{");
client.println("    order: 1;");
client.println("    width: 60%;");
client.println("  }");
client.println("  #rgbSettings #chooserForms .range{");
client.println("    margin: 10px 0 10px 0;");
client.println("  }");
client.println("  #rgbSettings #chooserForms .divider{");
client.println("    margin: 60px 0 60px 0;");
client.println("  }");
client.println("  #rgbSettings #submits{");
client.println("    order: 2;");
client.println("    width: 40%;");
client.println("    display: flex;");
client.println("    flex-flow: column;");
client.println("    margin: 115px 0 0 0;");
client.println("  }");
client.println("  #rgbSettings .button {");
client.println("    margin: 30px 30px 0 30px;");
client.println("    background-color: lightblue;");
client.println("    border: none;");
client.println("    color: white;");
client.println("    padding: 10px 20px;");
client.println("    text-align: center;");
client.println("    text-decoration: none;");
client.println("    font-size: 16px;");
client.println("  }");
client.println("  #rgbSettings .button:hover, #programmChoose .button:hover, #codeArea .button:hover {");
client.println("    background-color: dodgerblue;");
client.println("  }");
client.println("  #rgbSettings .button:active, #programmChoose .button:active, #codeArea .button:active{");
client.println("    background-color: darkblue;");
client.println("  }");
client.println("  #rgbSettings .rgbChoose{");
client.println("    display: flex;");
client.println("    flex-flow: column;");
client.println("  }");
client.println("  .hidden, .syncRGB{");
client.println("    display: none;");
client.println("  }");
client.println("  .slider {");
client.println("    -webkit-appearance: none;");
client.println("    width: 60%;");
client.println("    float: left;");
client.println("    height: 10px;");
client.println("    border-radius: 5px;");
client.println("    background: #d3d3d3;");
client.println("    outline: none;");
client.println("    opacity: 0.7;");
client.println("    -webkit-transition: .2s;");
client.println("    transition: opacity .2s;");
client.println("  }");
client.println("  .slider::-webkit-slider-thumb {");
client.println("    -webkit-appearance: none;");
client.println("    appearance: none;");
client.println("    width: 15px;");
client.println("    height: 15px;");
client.println("    border-radius: 30%;");
client.println("    background: lightskyblue;");
client.println("    cursor: pointer;");
client.println("  }");
client.println("  .slider::-moz-range-thumb {");
client.println("    width: 15px;");
client.println("    height: 15px;");
client.println("    border-radius: 30%;");
client.println("    background: lightskyblue;");
client.println("    cursor: pointer;");
client.println("  }");
client.println("</style>");
client.println("<main>");
client.println("  <h1>FIUS RGB</h1>");
client.println("  <div id=\"programmChoose\">");
client.println("    <form action=\"http://192.168.4.1/programm\" method=\"get\" class=\"choose\">");
client.println("      <div class=\"counterWrapper\">Prg. Nr.:");
client.println("        <label class=\"quantity\">");
client.print("          <input id=\"stepRanger\" type=\"number\" name=\"programm\" step=\"0\" min=\"0\"max=\"");
client.print(programmMaxIndex);
client.println("\" value=\"0\">");
client.println("        </label>");
client.println("      </div>");
client.println("      <input type=\"hidden\" name=\"last\" value=\"42\" />");
client.println("      <div class=\"submitWrapper\">");
client.println("        <label class=\"button\" for=\"button\">");
client.println("          <input id=\"button\" class=\"hidden\" type=\"submit\"/>Ausw&auml;hlen");
client.println("        </label>");
client.println("      </div>");
client.println("    </form>");
client.println("  </div>");
client.println("  <div id=\"rgbSettings\">");
client.println("    <div id=\"chooserForms\">");
client.println("      <form action=\"http://192.168.4.1/rgbChoose\" method=\"get\" class=\"rgbChoose\">");
client.println("        <label class=\"range\">");
client.print("          <input type=\"range\" name=\"r1\" min=\"1\" max=\"100\" value=\"");
client.print(r1);
client.println("\" class=\"slider\" id=\"r1\">R");
client.println("          <span id=\"valueR1\"></span>");
client.println("        </label>");
client.println("        <label class=\"range\">");
client.print("          <input type=\"range\" name=\"g1\" min=\"1\" max=\"100\" value=\"");
client.print(g1);
client.println("\" class=\"slider\" id=\"g1\">G");
client.println("          <span id=\"valueG1\"></span>");
client.println("        </label>");
client.println("        <label class=\"range\">");
client.print("          <input type=\"range\" name=\"b1\" min=\"1\" max=\"100\" value=\"");
client.print(b1);
client.println("\" class=\"slider\" id=\"b1\">B");
client.println("          <span id=\"valueB1\"></span>");
client.println("        </label>");
client.println("        <label class=\"divider\">");
client.print("          <input type=\"range\" name=\"divider\" min=\"1\" max=\"100\" value=\"");
client.print(divide);
client.println("\" class=\"slider\" id=\"divider\"> Teilung");
client.println("          <span id=\"valueDivider\"></span>");
client.println("        </label>");
client.println("        <label class=\"range\">");
client.print("          <input type=\"range\" name=\"r2\" min=\"1\" max=\"100\" value=\"");
client.print(r2);
client.println("\" class=\"slider\" id=\"r2\">R");
client.println("          <span id=\"valueR2\"></span>");
client.println("        </label>");
client.println("        <label class=\"range\">");
client.print("          <input type=\"range\" name=\"g2\" min=\"1\" max=\"100\" value=\"");
client.print(g2);
client.println("\" class=\"slider\" id=\"g2\">G");
client.println("          <span id=\"valueG2\"></span>");
client.println("        </label>");
client.println("        <label class=\"range\">");
client.print("          <input type=\"range\" name=\"b2\" min=\"1\" max=\"100\" value=\"");
client.print(b2);
client.println("\" class=\"slider\" id=\"b2\">B");
client.println("          <span id=\"valueB2\"></span>");
client.println("        </label>");
client.println("        <input type=\"hidden\" name=\"last\" value=\"42\" />");
client.println("        <input type=\"submit\" id=\"submit-form2\" class=\"hidden\" />");
client.println("      </form>");
client.println("    </div>");
client.println("    <div id=\"submits\">");
client.println("      <label class=\"button\" for=\"submit-form2\" tabindex=\"0\">Submit</label>");
client.println("      <form action=\"http://192.168.4.1/syncRGB\" method=\"get\" class=\"syncRGB\">");
client.println("        <input name=\"syncRGB\" type=\"text\" value=\"syncRGB\"/>");
client.println("        <input type=\"hidden\" name=\"last\" value=\"42\" />");
client.println("        <input type=\"submit\" id=\"submit-form3\" class=\"hidden\" />");
client.println("      </form>");
client.println("      <label class=\"button\" for=\"submit-form3\" tabindex=\"0\">Sync</label>");
client.println("    </div>");
client.println("  </div>");
client.println("  <div id=\"codeArea\">");
client.println("    <form action=\"http://192.168.4.1/code\" method=\"get\" class=\"code\">");
client.println("      <label class=\"textArea\"><p>Code:</p>");
client.println("        <textarea name=\"codeInput\" rows=\"25\" cols=\"150\">");
client.println("       </textarea>");
client.println("      </label>");
client.println("      <input type=\"hidden\" name=\"last\" value=\"42\" />");
client.println("      <div class=\"submitWrapper\">");
client.println("        <label class=\"button\" for=\"scriptButton\">");
client.println("          <input id=\"scriptButton\" class=\"hidden\" type=\"submit\"/>Script ausf&uuml;hren");
client.println("        </label>");
client.println("      </div>");
client.println("    </form>");
client.println("  </div>");
client.println("</main>");


}

